name: 'Automatically create releases from either PR or Push events'
description: 'Run develop actions'
author: 'Bennett Benedict'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true
  ASSETS_LOCATION:
    description: 'Assets location if any'
    required: false
  SLACK_URL:
    description: 'Slack URL for releases'
    required: false
  GITHUB_RELEASES:
    description: 'If to create a GitHub releases or not'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'

branding:
  icon: 'package'
  color: 'gray-dark'